- hosts: apic
  gather_facts: no
  connection: local
  
  vars:
    aci_login: &aci_login
      hostname: '{{ apic_host }}'
      username: '{{ apic.bootstrap.user }}'
      private_key: "{{ apic.openssl.key }}"
      #password: '{{ apic_password }}'
      use_proxy: '{{ apic_use_proxy }}'
      validate_certs: '{{ apic_validate_certs }}'

  vars_files:
    - vars.yml     
  
  tasks: 
  - name: Query APIC
    aci_rest:
     <<: *aci_login
     method: get
     path: "{{ api_path.firmware_nodes }}"
    delegate_to: localhost    
    register: result

  - name: Filter Query
    set_fact:
      SW_ID: "{{ result | json_query(\"imdata[*].fabricNode.attributes | [?role!='controller'].id\") | to_json }}"
  
  - debug:
     var: SW_ID

  - name: Add ipv4 address to out of band mgmt interface
    cisco.aci.aci_static_node_mgmt_address:
      <<: *aci_login
      epg: default
      pod_id: 1
      type: out_of_band
      node_id: "{{ item }}"
      ipv4_address: "10.10.10.{{ item }}/24"
      ipv4_gw: "10.10.10.1"
      state: present
    loop: "{{ SW_ID }}"

      

  